import {
    Home, Car, ShoppingCart, Briefcase, Play, BookOpenText,
    HeartPulse, MonitorSmartphone, Plane, GraduationCap, Building2,
    PiggyBank, Utensils, Baby, Music, Cpu, Dumbbell, ShieldCheck,
    CircleEllipsis,
    Dog,
    Hammer,
    HelpingHand,
    LampDesk,
    LineChart,
    Scissors,
    Shirt,
    ShoppingBasket,
    Sparkles,
    CreditCard,
    Ticket
  } from 'lucide-react'
  
export const categoriaIcone = {
    Receita: <Briefcase size={18}  />,
    Moradia: <Home size={18} />,
    Transporte: <Car size={18}/>,
    Cartão:  <CreditCard size={18} />,
    Alimentação: <ShoppingCart size={18}  />,
    Lazer: <Play size={18}  />,
    Educação: <BookOpenText size={18} />,
    Saúde: <HeartPulse size={18} />,
    Assinaturas: <MonitorSmartphone size={18} />,
    Viagem: <Plane size={18} />,
    Faculdade: <GraduationCap size={18} />,
    Impostos: <Building2 size={18} />,
    Poupança: <PiggyBank size={18}  />,
    Restaurante: <Utensils size={18}  />,
    Infantil: <Baby size={18}/>,
    Música: <Music size={18}  />,
    Cinema: <Ticket size={18}/>,
    Tecnologia: <Cpu size={18}  />,
    Academia: <Dumbbell size={18}  />,
    Seguro: <ShieldCheck size={18}  />,
    'Assinaturas e serviços': <MonitorSmartphone size={18} />,
    Investimentos: <LineChart size={18}  />,
    Pets: <Dog size={18} />,
    'Cuidados pessoais': <Scissors size={18}  />,
    Beleza: <Sparkles size={18}  />,
    Serviços: <Hammer size={18}  />,
    Vestuário: <Shirt size={18}  />,
    Mercado: <ShoppingBasket size={18}  />,
    Utilidades: <LampDesk size={18}  />,
    Doação: <HelpingHand size={18}  />,
    Outros: <CircleEllipsis size={18}  />,
  }

export const categoriaCores: Record<string, string> = {
    Receita: '#22C55E',          
    Alimentação: '#34D399',       
    Moradia: '#F87171',          
    Transporte: '#60A5FA',       
    Assinaturas: '#A78BFA',      
    Lazer: '#FBBF24',             
    Saúde: '#4ADE80',            
    Educação: '#C084FC',         
    Viagem: '#3B82F6',            
    Impostos: '#F97316',          
    Seguro: '#64748B',            
    Tecnologia: '#0EA5E9',        
    Música: '#E879F9',            
    Academia: '#10B981',         
    Poupança: '#16A34A',         
    Infantil: '#FB7185',         
    Restaurante: '#FB923C',       
    Outros: '#94A3B8',           
  }
  